// Generated by npm run generate:endpoints. Do not edit manually.
import type { ApiEndpointDefinition, ApiModuleDefinition } from '@/src/types/api';

export const API_ENDPOINTS = [
  {
    "id": "auth-001",
    "path": "/auth/public-config",
    "methods": [
      "GET"
    ],
    "module": "auth",
    "auth": "public",
    "source": "实测",
    "notes": "站点公开配置：注册开关、邮箱验证、邀请码、站点名称",
    "pathVariables": []
  },
  {
    "id": "setup-002",
    "path": "/setup/status",
    "methods": [
      "GET"
    ],
    "module": "setup",
    "auth": "public",
    "source": "实测",
    "notes": "是否已初始化管理员",
    "pathVariables": []
  },
  {
    "id": "setup-003",
    "path": "/setup/admin",
    "methods": [
      "POST"
    ],
    "module": "setup",
    "auth": "public",
    "source": "前端推断",
    "notes": "初始化管理员：email、password、name",
    "pathVariables": []
  },
  {
    "id": "auth-004",
    "path": "/auth/login",
    "methods": [
      "POST"
    ],
    "module": "auth",
    "auth": "public",
    "source": "前端推断",
    "notes": "邮箱密码登录，设置 session Cookie",
    "pathVariables": []
  },
  {
    "id": "auth-005",
    "path": "/auth/register",
    "methods": [
      "POST"
    ],
    "module": "auth",
    "auth": "public",
    "source": "当前 Web",
    "notes": "注册：email、password、nickname、invite_code、code",
    "pathVariables": []
  },
  {
    "id": "auth-006",
    "path": "/auth/send-code",
    "methods": [
      "POST"
    ],
    "module": "auth",
    "auth": "public",
    "source": "当前 Web",
    "notes": "发送邮箱验证码：email、scene（register/reset）",
    "pathVariables": []
  },
  {
    "id": "auth-007",
    "path": "/auth/reset-password",
    "methods": [
      "POST"
    ],
    "module": "auth",
    "auth": "public",
    "source": "前端推断",
    "notes": "重置密码：email、code、password",
    "pathVariables": []
  },
  {
    "id": "auth-008",
    "path": "/auth/api-key-login",
    "methods": [
      "POST"
    ],
    "module": "auth",
    "auth": "public",
    "source": "前端推断",
    "notes": "API Key 快捷登录：api_key（aps_ 开头）",
    "pathVariables": []
  },
  {
    "id": "auth-009",
    "path": "/auth/logout",
    "methods": [
      "POST"
    ],
    "module": "auth",
    "auth": "session",
    "source": "前端推断",
    "notes": "退出登录",
    "pathVariables": []
  },
  {
    "id": "profile-010",
    "path": "/user/me",
    "methods": [
      "GET",
      "PATCH"
    ],
    "module": "profile",
    "auth": "session",
    "source": "前端确认",
    "notes": "当前用户资料：查看 / 更新昵称",
    "pathVariables": []
  },
  {
    "id": "key-overview-011",
    "path": "/key-overview/overview",
    "methods": [
      "GET"
    ],
    "module": "key-overview",
    "auth": "session",
    "source": "前端推断",
    "notes": "API Key 登录后的轻量总览",
    "pathVariables": []
  },
  {
    "id": "keys-012",
    "path": "/user/keys",
    "methods": [
      "GET",
      "POST"
    ],
    "module": "keys",
    "auth": "session",
    "source": "前端确认",
    "notes": "网关 API Key 列表 / 创建（secret 仅返回一次）",
    "pathVariables": []
  },
  {
    "id": "keys-013",
    "path": "/user/keys/${id}",
    "methods": [
      "PATCH",
      "DELETE"
    ],
    "module": "keys",
    "auth": "session",
    "source": "前端确认",
    "notes": "启停 / 删除 API Key",
    "pathVariables": [
      "id"
    ]
  },
  {
    "id": "models-014",
    "path": "/user/models",
    "methods": [
      "GET"
    ],
    "module": "models",
    "auth": "session",
    "source": "前端确认",
    "notes": "按 Provider 返回用户可见模型",
    "pathVariables": []
  },
  {
    "id": "models-015",
    "path": "/user/models/visibility",
    "methods": [
      "PUT"
    ],
    "module": "models",
    "auth": "session",
    "source": "前端确认",
    "notes": "更新单个模型隐藏状态",
    "pathVariables": []
  },
  {
    "id": "plans-016",
    "path": "/user/plans",
    "methods": [
      "GET"
    ],
    "module": "plans",
    "auth": "session",
    "source": "前端确认",
    "notes": "套餐计划列表",
    "pathVariables": []
  },
  {
    "id": "usage-017",
    "path": "/user/usage/overview",
    "methods": [
      "GET"
    ],
    "module": "usage",
    "auth": "session",
    "source": "前端确认",
    "notes": "用量概览：请求数、token、费用",
    "pathVariables": []
  },
  {
    "id": "usage-018",
    "path": "/user/usage/trend",
    "methods": [
      "GET"
    ],
    "module": "usage",
    "auth": "session",
    "source": "前端确认",
    "notes": "用量趋势，Query: from/to/range",
    "pathVariables": []
  },
  {
    "id": "usage-019",
    "path": "/user/usage/analysis",
    "methods": [
      "GET"
    ],
    "module": "usage",
    "auth": "session",
    "source": "前端确认",
    "notes": "用量分析",
    "pathVariables": []
  },
  {
    "id": "usage-020",
    "path": "/user/quotas",
    "methods": [
      "GET"
    ],
    "module": "usage",
    "auth": "session",
    "source": "前端确认",
    "notes": "当前用户额度限制",
    "pathVariables": []
  },
  {
    "id": "requests-021",
    "path": "/user/usage/events",
    "methods": [
      "GET"
    ],
    "module": "requests",
    "auth": "session",
    "source": "前端确认",
    "notes": "请求日志，Query: range/page/page_size/model/provider/api_key_id/failed",
    "pathVariables": []
  },
  {
    "id": "gateway-022",
    "path": "/v1/models",
    "methods": [
      "GET"
    ],
    "module": "gateway",
    "auth": "apikey",
    "source": "实测",
    "notes": "OpenAI 兼容模型列表",
    "pathVariables": []
  },
  {
    "id": "gateway-023",
    "path": "/v1/chat/completions",
    "methods": [
      "POST"
    ],
    "module": "gateway",
    "auth": "apikey",
    "source": "兼容协议",
    "notes": "OpenAI Chat Completions，支持 stream",
    "pathVariables": []
  },
  {
    "id": "gateway-024",
    "path": "/v1/messages",
    "methods": [
      "POST"
    ],
    "module": "gateway",
    "auth": "apikey",
    "source": "兼容协议",
    "notes": "Anthropic Messages，支持 stream",
    "pathVariables": []
  },
  {
    "id": "gateway-025",
    "path": "/v1/messages/count_tokens",
    "methods": [
      "POST"
    ],
    "module": "gateway",
    "auth": "apikey",
    "source": "兼容协议",
    "notes": "Anthropic Token 计数",
    "pathVariables": []
  },
  {
    "id": "gateway-026",
    "path": "/v1/responses",
    "methods": [
      "POST"
    ],
    "module": "gateway",
    "auth": "apikey",
    "source": "二进制确认",
    "notes": "OpenAI Responses API，支持流式事件",
    "pathVariables": []
  },
  {
    "id": "gateway-027",
    "path": "/v1/images/generations",
    "methods": [
      "POST"
    ],
    "module": "gateway",
    "auth": "apikey",
    "source": "兼容协议",
    "notes": "图像生成：model、prompt、n、size、response_format",
    "pathVariables": []
  },
  {
    "id": "admin-users-028",
    "path": "/admin/users",
    "methods": [
      "GET"
    ],
    "module": "admin-users",
    "auth": "session",
    "source": "前端确认",
    "notes": "用户列表",
    "pathVariables": []
  },
  {
    "id": "admin-users-029",
    "path": "/admin/users/${id}",
    "methods": [
      "PUT",
      "DELETE"
    ],
    "module": "admin-users",
    "auth": "session",
    "source": "当前 Web",
    "notes": "更新（role、status）/ 删除用户",
    "pathVariables": [
      "id"
    ]
  },
  {
    "id": "admin-users-030",
    "path": "/admin/users/${id}/balance",
    "methods": [
      "POST"
    ],
    "module": "admin-users",
    "auth": "session",
    "source": "前端确认",
    "notes": "调整用户余额",
    "pathVariables": [
      "id"
    ]
  },
  {
    "id": "admin-users-031",
    "path": "/admin/users/${id}/subscriptions",
    "methods": [
      "POST"
    ],
    "module": "admin-users",
    "auth": "session",
    "source": "前端确认",
    "notes": "为用户开通套餐订阅",
    "pathVariables": [
      "id"
    ]
  },
  {
    "id": "admin-invites-032",
    "path": "/admin/invites",
    "methods": [
      "GET",
      "POST"
    ],
    "module": "admin-invites",
    "auth": "session",
    "source": "前端确认",
    "notes": "邀请码列表 / 创建",
    "pathVariables": []
  },
  {
    "id": "admin-invites-033",
    "path": "/admin/invites/${id}",
    "methods": [
      "PUT",
      "DELETE"
    ],
    "module": "admin-invites",
    "auth": "session",
    "source": "当前 Web",
    "notes": "更新 / 删除邀请码",
    "pathVariables": [
      "id"
    ]
  },
  {
    "id": "admin-invites-034",
    "path": "/admin/invites/${id}/redemptions",
    "methods": [
      "GET"
    ],
    "module": "admin-invites",
    "auth": "session",
    "source": "前端确认",
    "notes": "邀请码使用记录",
    "pathVariables": [
      "id"
    ]
  },
  {
    "id": "admin-plans-035",
    "path": "/admin/plans",
    "methods": [
      "GET",
      "POST"
    ],
    "module": "admin-plans",
    "auth": "session",
    "source": "前端确认",
    "notes": "套餐列表 / 创建",
    "pathVariables": []
  },
  {
    "id": "admin-plans-036",
    "path": "/admin/plans/${id}",
    "methods": [
      "PUT",
      "DELETE"
    ],
    "module": "admin-plans",
    "auth": "session",
    "source": "当前 Web",
    "notes": "更新 / 删除套餐",
    "pathVariables": [
      "id"
    ]
  },
  {
    "id": "admin-accounts-037",
    "path": "/admin/accounts",
    "methods": [
      "GET",
      "POST"
    ],
    "module": "admin-accounts",
    "auth": "session",
    "source": "前端确认",
    "notes": "上游账号列表 / 创建",
    "pathVariables": []
  },
  {
    "id": "admin-accounts-038",
    "path": "/admin/accounts/${id}",
    "methods": [
      "PUT",
      "DELETE"
    ],
    "module": "admin-accounts",
    "auth": "session",
    "source": "当前 Web",
    "notes": "更新 / 删除账号",
    "pathVariables": [
      "id"
    ]
  },
  {
    "id": "admin-accounts-039",
    "path": "/admin/accounts/bulk",
    "methods": [
      "PUT"
    ],
    "module": "admin-accounts",
    "auth": "session",
    "source": "当前 Web",
    "notes": "批量更新账号",
    "pathVariables": []
  },
  {
    "id": "admin-accounts-040",
    "path": "/admin/accounts/import",
    "methods": [
      "POST"
    ],
    "module": "admin-accounts",
    "auth": "session",
    "source": "前端确认",
    "notes": "导入账号，支持 ?dry_run=1 预检",
    "pathVariables": []
  },
  {
    "id": "admin-accounts-041",
    "path": "/admin/accounts/export",
    "methods": [
      "POST"
    ],
    "module": "admin-accounts",
    "auth": "session",
    "source": "当前 Web",
    "notes": "导出账号，Body: ids",
    "pathVariables": []
  },
  {
    "id": "admin-accounts-042",
    "path": "/admin/accounts/recover",
    "methods": [
      "POST"
    ],
    "module": "admin-accounts",
    "auth": "session",
    "source": "前端确认",
    "notes": "批量恢复账号",
    "pathVariables": []
  },
  {
    "id": "admin-accounts-043",
    "path": "/admin/accounts/${id}/recover",
    "methods": [
      "POST"
    ],
    "module": "admin-accounts",
    "auth": "session",
    "source": "前端确认",
    "notes": "恢复单个账号",
    "pathVariables": [
      "id"
    ]
  },
  {
    "id": "admin-accounts-044",
    "path": "/admin/accounts/${id}/models",
    "methods": [
      "GET"
    ],
    "module": "admin-accounts",
    "auth": "session",
    "source": "前端确认",
    "notes": "账号可用模型",
    "pathVariables": [
      "id"
    ]
  },
  {
    "id": "admin-accounts-045",
    "path": "/admin/accounts/${id}/models/test",
    "methods": [
      "POST"
    ],
    "module": "admin-accounts",
    "auth": "session",
    "source": "前端确认",
    "notes": "测试账号模型",
    "pathVariables": [
      "id"
    ]
  },
  {
    "id": "admin-oauth-046",
    "path": "/admin/accounts/oauth/${provider}/start",
    "methods": [
      "POST"
    ],
    "module": "admin-oauth",
    "auth": "session",
    "source": "前端确认",
    "notes": "OAuth 导入：开始",
    "pathVariables": [
      "provider"
    ]
  },
  {
    "id": "admin-oauth-047",
    "path": "/admin/accounts/oauth/${provider}/poll",
    "methods": [
      "POST"
    ],
    "module": "admin-oauth",
    "auth": "session",
    "source": "当前 Web",
    "notes": "OAuth 导入：轮询状态，Body: session_id",
    "pathVariables": [
      "provider"
    ]
  },
  {
    "id": "admin-oauth-048",
    "path": "/admin/accounts/oauth/${provider}/submit",
    "methods": [
      "POST"
    ],
    "module": "admin-oauth",
    "auth": "session",
    "source": "前端确认",
    "notes": "OAuth 导入：提交",
    "pathVariables": [
      "provider"
    ]
  },
  {
    "id": "admin-oauth-049",
    "path": "/admin/accounts/kiro/sso/start",
    "methods": [
      "POST"
    ],
    "module": "admin-oauth",
    "auth": "session",
    "source": "前端确认",
    "notes": "Kiro SSO：开始",
    "pathVariables": []
  },
  {
    "id": "admin-oauth-050",
    "path": "/admin/accounts/kiro/sso/poll",
    "methods": [
      "POST"
    ],
    "module": "admin-oauth",
    "auth": "session",
    "source": "当前 Web",
    "notes": "Kiro SSO：轮询",
    "pathVariables": []
  },
  {
    "id": "admin-oauth-051",
    "path": "/admin/accounts/kiro/sso/submit",
    "methods": [
      "POST"
    ],
    "module": "admin-oauth",
    "auth": "session",
    "source": "前端确认",
    "notes": "Kiro SSO：提交",
    "pathVariables": []
  },
  {
    "id": "admin-oauth-052",
    "path": "/admin/accounts/kiro/sso/cancel",
    "methods": [
      "POST"
    ],
    "module": "admin-oauth",
    "auth": "session",
    "source": "前端确认",
    "notes": "Kiro SSO：取消",
    "pathVariables": []
  },
  {
    "id": "admin-oauth-053",
    "path": "/admin/accounts/kiro/sso/select-profile",
    "methods": [
      "POST"
    ],
    "module": "admin-oauth",
    "auth": "session",
    "source": "前端确认",
    "notes": "Kiro SSO：选择 Profile",
    "pathVariables": []
  },
  {
    "id": "admin-oauth-054",
    "path": "/admin/accounts/kiro/sso-token",
    "methods": [
      "POST"
    ],
    "module": "admin-oauth",
    "auth": "session",
    "source": "前端确认",
    "notes": "Kiro：提交 SSO Token",
    "pathVariables": []
  },
  {
    "id": "admin-oauth-055",
    "path": "/admin/accounts/kiro/api-key",
    "methods": [
      "POST"
    ],
    "module": "admin-oauth",
    "auth": "session",
    "source": "前端确认",
    "notes": "Kiro：提交 API Key",
    "pathVariables": []
  },
  {
    "id": "admin-oauth-056",
    "path": "/admin/accounts/kiro/iam-sso/start",
    "methods": [
      "POST"
    ],
    "module": "admin-oauth",
    "auth": "session",
    "source": "前端确认",
    "notes": "Kiro IAM SSO：开始",
    "pathVariables": []
  },
  {
    "id": "admin-oauth-057",
    "path": "/admin/accounts/kiro/iam-sso/complete",
    "methods": [
      "POST"
    ],
    "module": "admin-oauth",
    "auth": "session",
    "source": "前端确认",
    "notes": "Kiro IAM SSO：完成",
    "pathVariables": []
  },
  {
    "id": "admin-oauth-058",
    "path": "/admin/accounts/oauth/kiro/start",
    "methods": [
      "POST"
    ],
    "module": "admin-oauth",
    "auth": "session",
    "source": "当前 Web",
    "notes": "Kiro OAuth：开始",
    "pathVariables": []
  },
  {
    "id": "admin-oauth-059",
    "path": "/admin/accounts/oauth/kiro/poll",
    "methods": [
      "POST"
    ],
    "module": "admin-oauth",
    "auth": "session",
    "source": "当前 Web",
    "notes": "Kiro OAuth：轮询",
    "pathVariables": []
  },
  {
    "id": "admin-providers-060",
    "path": "/admin/providers",
    "methods": [
      "GET",
      "POST"
    ],
    "module": "admin-providers",
    "auth": "session",
    "source": "前端确认",
    "notes": "Provider 列表 / 创建",
    "pathVariables": []
  },
  {
    "id": "admin-providers-061",
    "path": "/admin/providers/${id}",
    "methods": [
      "PUT",
      "DELETE"
    ],
    "module": "admin-providers",
    "auth": "session",
    "source": "当前 Web",
    "notes": "更新 / 删除 Provider",
    "pathVariables": [
      "id"
    ]
  },
  {
    "id": "admin-providers-062",
    "path": "/admin/providers/builtin",
    "methods": [
      "GET"
    ],
    "module": "admin-providers",
    "auth": "session",
    "source": "前端确认",
    "notes": "内置 Provider 列表",
    "pathVariables": []
  },
  {
    "id": "admin-providers-063",
    "path": "/admin/providers/builtin/${name}/models",
    "methods": [
      "GET",
      "PUT"
    ],
    "module": "admin-providers",
    "auth": "session",
    "source": "当前 Web",
    "notes": "查看 / 更新内置 Provider 模型",
    "pathVariables": [
      "name"
    ]
  },
  {
    "id": "admin-providers-064",
    "path": "/admin/providers/builtin/${name}/route-prefix",
    "methods": [
      "PUT"
    ],
    "module": "admin-providers",
    "auth": "session",
    "source": "前端确认",
    "notes": "内置 Provider 路由前缀",
    "pathVariables": [
      "name"
    ]
  },
  {
    "id": "admin-providers-065",
    "path": "/admin/providers/${id}/quota-test",
    "methods": [
      "POST"
    ],
    "module": "admin-providers",
    "auth": "session",
    "source": "前端确认",
    "notes": "Provider 额度查询测试",
    "pathVariables": [
      "id"
    ]
  },
  {
    "id": "admin-proxies-066",
    "path": "/admin/proxies",
    "methods": [
      "GET",
      "POST"
    ],
    "module": "admin-proxies",
    "auth": "session",
    "source": "前端确认",
    "notes": "代理列表 / 创建",
    "pathVariables": []
  },
  {
    "id": "admin-proxies-067",
    "path": "/admin/proxies/${id}",
    "methods": [
      "PUT",
      "DELETE"
    ],
    "module": "admin-proxies",
    "auth": "session",
    "source": "当前 Web",
    "notes": "更新 / 删除代理",
    "pathVariables": [
      "id"
    ]
  },
  {
    "id": "admin-proxies-068",
    "path": "/admin/proxies/${id}/impact",
    "methods": [
      "GET"
    ],
    "module": "admin-proxies",
    "auth": "session",
    "source": "前端确认",
    "notes": "删除代理的影响评估",
    "pathVariables": [
      "id"
    ]
  },
  {
    "id": "admin-proxies-069",
    "path": "/admin/proxies/${id}/test",
    "methods": [
      "POST"
    ],
    "module": "admin-proxies",
    "auth": "session",
    "source": "前端确认",
    "notes": "测试代理连通性",
    "pathVariables": [
      "id"
    ]
  },
  {
    "id": "admin-proxies-070",
    "path": "/admin/proxies/system",
    "methods": [
      "PUT"
    ],
    "module": "admin-proxies",
    "auth": "session",
    "source": "前端确认",
    "notes": "系统级代理配置",
    "pathVariables": []
  },
  {
    "id": "admin-models-071",
    "path": "/admin/models",
    "methods": [
      "GET",
      "PUT",
      "DELETE"
    ],
    "module": "admin-models",
    "auth": "session",
    "source": "当前 Web",
    "notes": "查询 / 保存 / 删除模型；删除使用 id、provider Query",
    "pathVariables": []
  },
  {
    "id": "admin-models-072",
    "path": "/admin/models/sync",
    "methods": [
      "POST"
    ],
    "module": "admin-models",
    "auth": "session",
    "source": "前端确认",
    "notes": "同步模型目录",
    "pathVariables": []
  },
  {
    "id": "admin-models-073",
    "path": "/admin/models/probe",
    "methods": [
      "POST"
    ],
    "module": "admin-models",
    "auth": "session",
    "source": "前端确认",
    "notes": "探测模型",
    "pathVariables": []
  },
  {
    "id": "admin-models-074",
    "path": "/admin/models/cleanup",
    "methods": [
      "POST"
    ],
    "module": "admin-models",
    "auth": "session",
    "source": "前端确认",
    "notes": "清理失效模型",
    "pathVariables": []
  },
  {
    "id": "admin-models-075",
    "path": "/admin/models/enabled",
    "methods": [
      "PUT"
    ],
    "module": "admin-models",
    "auth": "session",
    "source": "前端确认",
    "notes": "批量启用/禁用模型",
    "pathVariables": []
  },
  {
    "id": "admin-models-076",
    "path": "/admin/models/provider-enabled",
    "methods": [
      "PUT"
    ],
    "module": "admin-models",
    "auth": "session",
    "source": "当前 Web",
    "notes": "按 Provider 批量启用/禁用模型",
    "pathVariables": []
  },
  {
    "id": "admin-models-077",
    "path": "/admin/snapshot/warnings",
    "methods": [
      "GET"
    ],
    "module": "admin-models",
    "auth": "session",
    "source": "前端确认",
    "notes": "快照警告",
    "pathVariables": []
  },
  {
    "id": "admin-stats-078",
    "path": "/admin/stats/overview",
    "methods": [
      "GET"
    ],
    "module": "admin-stats",
    "auth": "session",
    "source": "前端确认",
    "notes": "统计概览",
    "pathVariables": []
  },
  {
    "id": "admin-stats-079",
    "path": "/admin/stats/trend",
    "methods": [
      "GET"
    ],
    "module": "admin-stats",
    "auth": "session",
    "source": "前端确认",
    "notes": "统计趋势",
    "pathVariables": []
  },
  {
    "id": "admin-stats-080",
    "path": "/admin/stats/analysis",
    "methods": [
      "GET"
    ],
    "module": "admin-stats",
    "auth": "session",
    "source": "前端确认",
    "notes": "统计分析",
    "pathVariables": []
  },
  {
    "id": "admin-stats-081",
    "path": "/admin/usage/overview/realtime",
    "methods": [
      "GET"
    ],
    "module": "admin-stats",
    "auth": "session",
    "source": "前端确认",
    "notes": "实时用量概览",
    "pathVariables": []
  },
  {
    "id": "admin-stats-082",
    "path": "/admin/usage/events",
    "methods": [
      "GET"
    ],
    "module": "admin-stats",
    "auth": "session",
    "source": "前端确认",
    "notes": "用量事件列表",
    "pathVariables": []
  },
  {
    "id": "admin-stats-083",
    "path": "/admin/usage/events/export",
    "methods": [
      "GET"
    ],
    "module": "admin-stats",
    "auth": "session",
    "source": "前端确认",
    "notes": "导出用量事件",
    "pathVariables": []
  },
  {
    "id": "admin-logs-084",
    "path": "/admin/logs/app",
    "methods": [
      "GET"
    ],
    "module": "admin-logs",
    "auth": "session",
    "source": "前端确认",
    "notes": "应用日志，支持 ?stream=true",
    "pathVariables": []
  },
  {
    "id": "admin-logs-085",
    "path": "/admin/traces",
    "methods": [
      "GET"
    ],
    "module": "admin-logs",
    "auth": "session",
    "source": "前端确认",
    "notes": "Trace 列表",
    "pathVariables": []
  },
  {
    "id": "admin-logs-086",
    "path": "/admin/traces/${id}",
    "methods": [
      "GET"
    ],
    "module": "admin-logs",
    "auth": "session",
    "source": "前端确认",
    "notes": "Trace 详情",
    "pathVariables": [
      "id"
    ]
  },
  {
    "id": "admin-quota-087",
    "path": "/admin/quota",
    "methods": [
      "GET"
    ],
    "module": "admin-quota",
    "auth": "session",
    "source": "前端确认",
    "notes": "额度概览",
    "pathVariables": []
  },
  {
    "id": "admin-quota-088",
    "path": "/admin/quota/refresh",
    "methods": [
      "POST"
    ],
    "module": "admin-quota",
    "auth": "session",
    "source": "前端确认",
    "notes": "刷新额度",
    "pathVariables": []
  },
  {
    "id": "admin-config-089",
    "path": "/admin/config",
    "methods": [
      "GET",
      "PUT"
    ],
    "module": "admin-config",
    "auth": "session",
    "source": "前端确认",
    "notes": "系统配置查看 / 更新",
    "pathVariables": []
  },
  {
    "id": "admin-config-090",
    "path": "/admin/config/validate",
    "methods": [
      "POST"
    ],
    "module": "admin-config",
    "auth": "session",
    "source": "前端确认",
    "notes": "校验配置",
    "pathVariables": []
  },
  {
    "id": "admin-config-091",
    "path": "/admin/email/settings",
    "methods": [
      "GET",
      "PUT"
    ],
    "module": "admin-config",
    "auth": "session",
    "source": "前端确认",
    "notes": "邮件设置",
    "pathVariables": []
  },
  {
    "id": "admin-config-092",
    "path": "/admin/email/test",
    "methods": [
      "POST"
    ],
    "module": "admin-config",
    "auth": "session",
    "source": "前端确认",
    "notes": "发送测试邮件",
    "pathVariables": []
  },
  {
    "id": "admin-config-093",
    "path": "/admin/email/preview",
    "methods": [
      "POST"
    ],
    "module": "admin-config",
    "auth": "session",
    "source": "前端确认",
    "notes": "预览邮件模板",
    "pathVariables": []
  },
  {
    "id": "admin-config-094",
    "path": "/admin/email/templates/defaults",
    "methods": [
      "GET"
    ],
    "module": "admin-config",
    "auth": "session",
    "source": "前端确认",
    "notes": "默认邮件模板",
    "pathVariables": []
  },
  {
    "id": "admin-config-095",
    "path": "/admin/github/settings",
    "methods": [
      "GET",
      "PUT"
    ],
    "module": "admin-config",
    "auth": "session",
    "source": "前端确认",
    "notes": "GitHub 集成设置",
    "pathVariables": []
  },
  {
    "id": "admin-system-096",
    "path": "/admin/system/info",
    "methods": [
      "GET"
    ],
    "module": "admin-system",
    "auth": "session",
    "source": "前端确认",
    "notes": "系统信息：版本、环境、数据库",
    "pathVariables": []
  },
  {
    "id": "admin-system-097",
    "path": "/admin/system/check-updates",
    "methods": [
      "GET"
    ],
    "module": "admin-system",
    "auth": "session",
    "source": "前端确认",
    "notes": "检查更新，Query: force=true|false",
    "pathVariables": []
  },
  {
    "id": "admin-system-098",
    "path": "/admin/system/update-settings",
    "methods": [
      "GET",
      "PUT"
    ],
    "module": "admin-system",
    "auth": "session",
    "source": "前端确认",
    "notes": "自动更新设置",
    "pathVariables": []
  },
  {
    "id": "admin-system-099",
    "path": "/admin/system/update",
    "methods": [
      "POST"
    ],
    "module": "admin-system",
    "auth": "session",
    "source": "前端确认",
    "notes": "执行更新",
    "pathVariables": []
  },
  {
    "id": "admin-system-100",
    "path": "/admin/system/restart",
    "methods": [
      "POST"
    ],
    "module": "admin-system",
    "auth": "session",
    "source": "前端确认",
    "notes": "重启服务",
    "pathVariables": []
  },
  {
    "id": "admin-system-101",
    "path": "/admin/system/rollback",
    "methods": [
      "POST"
    ],
    "module": "admin-system",
    "auth": "session",
    "source": "前端确认",
    "notes": "回滚版本",
    "pathVariables": []
  },
  {
    "id": "admin-tokens-102",
    "path": "/admin/management-tokens",
    "methods": [
      "GET",
      "POST"
    ],
    "module": "admin-tokens",
    "auth": "session",
    "source": "前端确认",
    "notes": "管理 Token 列表 / 创建（token 仅返回一次）",
    "pathVariables": []
  },
  {
    "id": "admin-tokens-103",
    "path": "/admin/management-tokens/${id}",
    "methods": [
      "DELETE"
    ],
    "module": "admin-tokens",
    "auth": "session",
    "source": "前端确认",
    "notes": "删除管理 Token",
    "pathVariables": [
      "id"
    ]
  },
  {
    "id": "admin-tokens-104",
    "path": "/admin/management-tokens/${id}/revoke",
    "methods": [
      "POST"
    ],
    "module": "admin-tokens",
    "auth": "session",
    "source": "前端确认",
    "notes": "撤销管理 Token",
    "pathVariables": [
      "id"
    ]
  }
] as const satisfies readonly ApiEndpointDefinition[];

export const API_MODULES = [
  {
    "key": "auth",
    "label": "认证",
    "endpointCount": 7,
    "methodCount": 7
  },
  {
    "key": "setup",
    "label": "初始化",
    "endpointCount": 2,
    "methodCount": 2
  },
  {
    "key": "profile",
    "label": "个人资料",
    "endpointCount": 1,
    "methodCount": 2
  },
  {
    "key": "key-overview",
    "label": "Key 总览",
    "endpointCount": 1,
    "methodCount": 1
  },
  {
    "key": "keys",
    "label": "API Key",
    "endpointCount": 2,
    "methodCount": 4
  },
  {
    "key": "models",
    "label": "模型",
    "endpointCount": 2,
    "methodCount": 2
  },
  {
    "key": "plans",
    "label": "套餐 / 余额",
    "endpointCount": 1,
    "methodCount": 1
  },
  {
    "key": "usage",
    "label": "用量",
    "endpointCount": 4,
    "methodCount": 4
  },
  {
    "key": "requests",
    "label": "请求日志",
    "endpointCount": 1,
    "methodCount": 1
  },
  {
    "key": "gateway",
    "label": "AI 网关（/v1）",
    "endpointCount": 6,
    "methodCount": 6
  },
  {
    "key": "admin-users",
    "label": "管理 · 用户",
    "endpointCount": 4,
    "methodCount": 5
  },
  {
    "key": "admin-invites",
    "label": "管理 · 邀请码",
    "endpointCount": 3,
    "methodCount": 5
  },
  {
    "key": "admin-plans",
    "label": "管理 · 套餐",
    "endpointCount": 2,
    "methodCount": 4
  },
  {
    "key": "admin-accounts",
    "label": "管理 · 上游账号",
    "endpointCount": 9,
    "methodCount": 11
  },
  {
    "key": "admin-oauth",
    "label": "管理 · OAuth / Kiro 导入",
    "endpointCount": 14,
    "methodCount": 14
  },
  {
    "key": "admin-providers",
    "label": "管理 · Providers",
    "endpointCount": 6,
    "methodCount": 9
  },
  {
    "key": "admin-proxies",
    "label": "管理 · 代理",
    "endpointCount": 5,
    "methodCount": 7
  },
  {
    "key": "admin-models",
    "label": "管理 · 模型目录",
    "endpointCount": 7,
    "methodCount": 9
  },
  {
    "key": "admin-stats",
    "label": "管理 · 统计 / 用量",
    "endpointCount": 6,
    "methodCount": 6
  },
  {
    "key": "admin-logs",
    "label": "管理 · 日志 / Trace",
    "endpointCount": 3,
    "methodCount": 3
  },
  {
    "key": "admin-quota",
    "label": "管理 · 额度",
    "endpointCount": 2,
    "methodCount": 2
  },
  {
    "key": "admin-config",
    "label": "管理 · 配置 / 邮件",
    "endpointCount": 7,
    "methodCount": 10
  },
  {
    "key": "admin-system",
    "label": "管理 · 系统",
    "endpointCount": 6,
    "methodCount": 7
  },
  {
    "key": "admin-tokens",
    "label": "管理 · Management Tokens",
    "endpointCount": 3,
    "methodCount": 4
  }
] as const satisfies readonly ApiModuleDefinition[];
